# Generated by Django 4.1.5 on 2023-01-15 09:28

from django.db import migrations, models
import song.models


class Migration(migrations.Migration):

    dependencies = [
        ("song", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="file",
            field=models.FileField(upload_to=song.models.song_path),
        ),
    ]
