# Generated by Django 4.1.5 on 2023-01-15 10:06

import django.core.validators
from django.db import migrations, models
import song.models


class Migration(migrations.Migration):

    dependencies = [
        ("song", "0003_song_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="title",
            field=models.CharField(default="Dummy Song", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="song",
            name="file",
            field=models.FileField(
                upload_to=song.models.song_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "mp3",
                            "mp4",
                            "wav",
                            "aac",
                            "wma",
                            "flac",
                            "m4a",
                        ]
                    ),
                    song.models.song_size_limiter,
                ],
            ),
        ),
    ]
