# Generated by Django 4.1.5 on 2023-01-19 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("song", "0007_song_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="song",
            options={"ordering": ("-created_at",)},
        ),
    ]
