# Generated by Django 4.1.5 on 2023-01-20 02:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("song", "0008_alter_song_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="liked_by",
            field=models.ManyToManyField(
                related_name="liked_songs", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
