# Generated by Django 4.1.5 on 2023-01-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("song", "0011_playhistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="title",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
