# Generated by Django 4.1.5 on 2023-01-20 03:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("station", "0002_station_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="subscribed_by",
            field=models.ManyToManyField(
                related_name="subscribed_stations", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
