# Generated by Django 4.1.5 on 2023-01-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station", "0003_station_subscribed_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="station",
            name="name",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
