# Generated by Django 4.1.5 on 2023-01-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userid", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=25)),
            ],
            options={
                "db_table": "user_profile",
                "ordering": ["userid"],
            },
        ),
    ]
