# Generated by Django 4.1.5 on 2023-01-21 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_rename_user_userprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
